# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f33dc470eb34e1084328ae77c878c9c79ce91eacdfbe8e00c4f523476f082e5a8c708a2e1c5ef4768693b32d90eff3d81b5240c9ed5a6c57335f264b01711a7e

test:
  secret_key_base: 01197b1c7fa994d444f5aa0a90a0c75a0516adf8c65c65a1cd7666231d6c12070b5da80cedd694b0e5abc0c4b861fe58b0cb12670b2d3e2ee99091f0dab855f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
